# - Find cfitsio
# Find the native CFITSIO includes and library
#
#  CFITSIO_FOUND         = True if cfitsio found
#  CFITSIO_LIBRARIES     = Set of libraries required for linking
#  CFITSIO_INCLUDE_DIR   = Directory where to find fitsio.h

# Already in cache, be silent
#IF (CFITSIO_INCLUDE_DIR)
#    SET(CFITSIO_FIND_QUIETLY TRUE)
#ENDIF (CFITSIO_INCLUDE_DIR)

FIND_PATH(CFITSIO_INCLUDE_DIR fitsio.h PATHS /usr/include/ )

SET(CFITSIO_NAMES cfitsio)
    
FOREACH(lib ${CFITSIO_NAMES} )
    FIND_LIBRARY(CFITSIO_LIBRARY_${lib} NAMES ${lib})
    LIST(APPEND CFITSIO_LIBRARIES ${CFITSIO_LIBRARY_${lib}})
ENDFOREACH(lib)

# handle the QUIETLY and REQUIRED arguments and set CFITSIO_FOUND to TRUE if.
# all listed variables are TRUE
INCLUDE(FindPackageHandleCompat)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CFITSIO DEFAULT_MSG CFITSIO_LIBRARIES CFITSIO_INCLUDE_DIR)

IF(NOT CFITSIO_FOUND)
    SET( CFITSIO_LIBRARIES )
ENDIF(NOT CFITSIO_FOUND)

MARK_AS_ADVANCED(CFITSIO_LIBRARIES CFITSIO_INCLUDE_DIR)
