#!/usr/bin/perl
# Create a template for a new doxygen page
# Given a name will return the location
# of the appropriatedoxygen file 
# If the files do not exist it will create them with
# a standard template
# -----------------------------------------------
# copyright Chirs Williams 2003-2009
# -----------------------------------------------

use FileHandle;
use Cwd;

sub usage {
    print "Funtion:\n";
    print "  Return the filenames of the specified doxygen page.\n";
    print "  If the file does not exist then it will be generated.\n";
    print "  with a standard template.\n";
    print "Usage:\n",
          "  newpage tag title\n";
    print "Options:\n",
          "  --help \t: dsiplay this message\n",
          "  -f filename\t: specify an alternative filename\n",
          "  -t template\t: specify an alternative template\n",
          "                 Templates available:\n",
          "                   main\n",
          "\n";
    print "Examples:\n";
    print "    >newpage intro Introduction\n\n";
    print "    Will create the file intro.doxy in the current dir\n";
    print "    the page title will be \"Introduction\" and will be\n";
    print "    reference tagged with the keyword \"intro\"\n";
}

my $doxy_file;
my $pagetype="page";
my $tagged=1;
while ( $ARGV[0] =~/^-(.+)/ )
{
    shift @ARGV;
    my $opt=$1;
    if ( $opt =~/^-+help/ ) {
        usage();
        exit 0;
    }
    elsif ( $opt =~/^-f/ ) {
        $doxy_file = shift @ARGV;
        next;
    }
    elsif ( $opt eq "t" ) {
        # templates
        my $template = shift;
        if ( $template eq "main" ) {
           $pagetype="mainpage";
           $tagged=0;
        }
    }
}
if ( $#ARGV != 1 ) { 
    print "Expecting different number of arguments. Got : ( @ARGV )\n";
    usage(); 
    exit 1;
}
my $tag=shift @ARGV;
my $title=shift @ARGV;
if( ! defined $doxy_file ) {
   $doxy_file = $tag.".doxy";
}

if ( ! -f $doxy_file ) {
    my $fh=FileHandle->new(">".$doxy_file) or die "unable to create $doxy_file : $!\n";
    print $fh "/**\n",
              '@',$pagetype,($tagged?" ".$tag:"")," ", $title,"\n\n",
               "\n*/\n";
}
print $doxy_file,"\n";

